common/models/Post.php
<?php

namespace common\models;

use HTMLPurifier_Config;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\SluggableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * Class Post
 * @package common\models
 * @property integer $id
 * @property string $slug
 * @property string $image
 * @property string $title
 * @property string $body
 * @property string $seo_description
 * @property string $seo_keywords
 * @property string $seo_title
 * @property integer $status
 * @property integer $user_id
 * @property string $created_at
 * @property string $updated_at
 * @property string $published_at
 * @property int $rate_sum
 * @property int $rate_count
 */
class Post extends ActiveRecord
{
    public const DELIMITER = '_____DELIMITER_____';
    public const STATUS_DRAFT = 0;
    public const STATUS_PUBLISHED = 1;
    public const STATUS_DELETED = 2;

    /**
     * @return PostQuery
     */
    public static function find()
    {
        return new PostQuery(static::class);
    }

    public static function tableName(): string
    {
        return '{{%post}}';
    }

    public function rules(): array
    {
        return [
            [['title', 'seo_description', 'seo_keywords', 'seo_title'], 'trim'],
            [['title', 'seo_description', 'seo_keywords', 'seo_title', 'body',], 'required'],
            [['title', 'seo_description', 'seo_keywords', 'seo_title', 'image'], 'string', 'max' => 255],
            ['image', 'default', 'value' => ''],
            [
                'body',
                'filter',
                'filter' => function ($value) {
                    return \yii\helpers\HtmlPurifier::process(
                        $value,
                        function (HTMLPurifier_Config $config) {
                        }
                    );
                },
            ],
            ['body', 'safe'],
            ['status', 'default', 'value' => self::STATUS_DRAFT],
            ['status', 'in', 'range' => array_keys(static::getStatusList())],
        ];
    }

    public static function getStatusList(): array
    {
        return [
            self::STATUS_DRAFT => 'Черновик',
            self::STATUS_PUBLISHED => 'Опубликован',
            self::STATUS_DELETED => 'Удален',
        ];
    }

    public function attributeLabels(): array
    {
        return [
            'title' => 'Заголовок',
            'image' => 'Картинка',
            'status' => 'Статус',
            'created_at' => 'Создан',
            'updated_at' => 'Изменен',
            'published_at' => 'Опубликован',
        ];
    }

    public function behaviors(): array
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => function () {
                    return date('Y-m-d H:i:s');
                },
            ],
            [
                'class' => BlameableBehavior::class,
                'createdByAttribute' => 'user_id',
                'updatedByAttribute' => 'user_id',
            ],
            [
                'class' => SluggableBehavior::class,
                'attribute' => 'title',
                'ensureUnique' => true,
            ],
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->status == self::STATUS_PUBLISHED && !$this->published_at) {
            $this->published_at = date('Y-m-d H:i:s');
        }

        return parent::beforeSave($insert);
    }

    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'user_id']);
    }

    public function getRate()
    {
        return $this->rate_count ? round($this->rate_sum / $this->rate_count) : 0;
    }

    public function getFormattedRateCount()
    {
        return \Yii::t(
            'app',
            '{n, plural, =0{нет оценок} =1{одна оценка} one{# оценка} few{# оценки} many{# оценок} other{# оценки}}',
            ['n' => $this->rate_count]
        );
    }
}

backend/controllers/PostController.php
<?php

namespace backend\controllers;

use backend\models\PostSearch;
use common\models\Post;
use common\models\User;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class PostController extends Controller
{
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'denyCallback' => function () {
                    \Yii::$app->user->loginRequired();
                },
                'rules' => [
                    ['actions' => ['index'], 'allow' => true, 'roles' => [User::POST_LIST]],
                    ['actions' => ['create'], 'allow' => true, 'roles' => [User::POST_CREATE]],
                    ['actions' => ['update'], 'allow' => true, 'roles' => [User::POST_UPDATE]],
                ],
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(\Yii::$app->request->queryParams);

        return $this->render('index', ['dataProvider' => $dataProvider, 'searchModel' => $searchModel]);
    }

    /**
     * @return string
     */
    public function actionCreate()
    {
        $model = new Post();
        if ($model->load(\Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('create', ['model' => $model]);
    }

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        /** @var Post $model */
        $model = Post::findOne($id);
        if (!$model) {
            throw new NotFoundHttpException('Пост не найдена');
        }
        if ($model->load(\Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('update', ['model' => $model]);
    }
}

frontend/controllers/PostController.php
<?php

namespace frontend\controllers;

use common\models\Post;
use common\models\Seo;
use frontend\models\PostRate;
use frontend\models\PostSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class PostController extends Controller
{
    /**
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(\Yii::$app->request->getQueryParams());
        $seo = Seo::findOne(['page' => Seo::BLOG_PAGE]);

        return $this->render('index', ['dataProvider' => $dataProvider, 'seo' => $seo]);
    }

    /**
     * @param $slug
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionView($slug)
    {
        /** @var Post $model */
        $model = Post::find()->published()->slug($slug)->one();
        if (!$model) {
            throw new NotFoundHttpException;
        }
        $seo = Seo::findOne(['page' => Seo::BLOG_PAGE]);

        return $this->render('view', ['model' => $model, 'seo' => $seo]);
    }

    /**
     * @param $id
     * @return array
     */
    public function actionRate($id)
    {
        $model = new PostRate(['id' => $id]);
        \Yii::$app->response->format = Response::FORMAT_JSON;
        if ($model->load(\Yii::$app->request->post(), '') && $model->save()) {
            return [
                'success' => true,
                'rate' => $model->getPostRate(),
                'count' => $model->getPostRateCount(),
            ];
        }

        return ['success' => false, 'errors' => $model->getErrors()];
    }
}

backend/views/post/_form.php
<?php

use backend\widgets\Select;
use yii\helpers\Html;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/**
 * @var $this yii\web\View
 * @var $model common\models\Post
 * @var $form yii\widgets\ActiveForm
 */
$params = Json::encode(
    [
        'minHeight' => '500px',
        'imageUpload' => Url::to(['site/upload']),
        'uploadImageFields' => [Yii::$app->request->csrfParam => Yii::$app->request->csrfToken,],
    ]
);
$this->registerJs('$("#js-redactor").redactor('.$params.');');
$image = $model->image ?: null;
$imageUrl = $model->image ? Url::to(['image/view', 'name' => $model->image]) : null;
$script = <<< END
function getCsrfParam() {
    return $("meta[name=csrf-param]").attr("content");
}

function getCsrfToken() {
    return $("meta[name=csrf-token]").attr("content");
}

var app = new Vue({
  el: '#js-image',
  data: {
    image: '{$image}',
    imageUrl: '{$imageUrl}',
  },
  methods: {
    removeImage() {
        this.image = '';
        this.imageUrl = '';
    },
    uploadImage() {
        var self = this;
        var input = $("<input type=\"file\">");
        input.change(function () {
            let formData = new FormData();
            formData.append("file", this.files[0]);
            formData.append(getCsrfParam(), getCsrfToken());
            $.ajax({
                url: "/site/upload",
                type: "post",
                contentType: false,
                processData: false,
                data: formData,
                dataType: "json"
            }).always(function () {
                input.remove();
            }).done(function (r) { 
                 self.image = r.filename;
                 self.imageUrl = r.filelink;
            });
        }).click();
    },
  }
})
END;

$this->registerJs($script);
?>

<?php $form = ActiveForm::begin(['options' => ['autocomplete' => 'off']]); ?>
<?= $form->field($model, 'title')->textInput(['class' => 'form-control input-sm']); ?>
<?= $form->field($model, 'seo_title')->textInput(['class' => 'form-control input-sm']); ?>
<?= $form->field($model, 'seo_description')->textInput(['class' => 'form-control input-sm']); ?>
<?= $form->field($model, 'seo_keywords')->textInput(['class' => 'form-control input-sm']); ?>
<div id="js-image">
    <?= $form->field($model, 'image')->hiddenInput(['v-model' => 'image']); ?>
    <img :src="imageUrl" width="300">
    <div>
        <button type="button" class="btn btn-sm btn-success" v-on:click="uploadImage()">Загрузить</button>
        <button type="button" class="btn btn-sm btn-warning" v-on:click="removeImage()">Удалить</button>
    </div>
</div>
<?= $form->field($model, 'body')->textarea(['class' => 'form-control input-sm', 'id' => 'js-redactor'])->hint(
    'В качестве разделителя контента используем '.Html::encode(\common\models\Post::DELIMITER)
); ?>
<?= $form->field($model, 'status')->widget(
    Select::class,
    [
        'options' => ['class' => 'form-control input-sm', 'data-style' => 'btn-sm btn-default'],
        'items' => $model::getStatusList(),
    ]
) ?>
<?= Html::submitButton($model->isNewRecord ? 'Добавить' : 'Обновить', ['class' => 'btn btn-sm btn-success']) ?>
<?= Html::a('Отмена', ['index'], ['class' => 'btn btn-sm btn-success']) ?>
<?php ActiveForm::end(); ?>

backend/views/post/_search.php
<?php

use backend\widgets\Select;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var $this yii\web\View
 * @var $model \backend\models\PostSearch
 * @var $form yii\widgets\ActiveForm
 */

$this->registerJs('jQuery("body").on("click", ".js-filter", function () { jQuery(".js-post-search").toggle(); });');
?>
<?= Html::a('Фильтр', '#', ['class' => 'btn btn-sm btn-success js-filter']) ?>
<div class="js-post-search" style="display: none;">
    <?php $form = ActiveForm::begin(['action' => ['index'], 'method' => 'get',]); ?>
    <section class="item">
        <div class="row">
            <div class="col-sm-2">
                <?= $form->field($model, 'title')->textInput(['class' => 'form-control input-sm']); ?>
            </div>
            <div class="col-sm-2">
                <?= $form->field($model, 'body')->textInput(['class' => 'form-control input-sm']); ?>
            </div>
            <div class="col-sm-2">
                <?= $form->field($model, 'seo_title')->textInput(['class' => 'form-control input-sm']); ?>
            </div>
            <div class="col-sm-2">
                <?= $form->field($model, 'seo_description')->textInput(['class' => 'form-control input-sm']); ?>
            </div>
            <div class="col-sm-2">
                <?= $form->field($model, 'seo_keywords')->textInput(['class' => 'form-control input-sm']); ?>
            </div>
            <div class="col-sm-2">
                <?= $form->field($model, 'status')->widget(
                    Select::class,
                    [
                        'options' => [
                            'class' => 'form-control input-sm',
                            'prompt' => 'Все',
                            'data-style' => 'btn-sm btn-default',
                        ],
                        'items' => $model::getStatusList(),
                    ]
                ) ?>
            </div>
            <div class="col-sm-1">
                <label for="" class="control-label">&nbsp;</label>
                <?= Html::submitButton('Найти', ['class' => 'btn btn-sm btn-primary']) ?>
            </div>
            <div class="col-sm-1">
                <label for="" class="control-label">&nbsp;</label>
                <?= Html::a('Сброс', ['post/index'], ['class' => 'btn btn-sm btn-default']) ?>
            </div>
        </div>
    </section>
    <?php ActiveForm::end(); ?>
</div>

backend/views/post/create.php
<?php
/**
 * @var $this \yii\web\View
 * @var $model
 */
$this->title = 'Новый пост';
echo $this->render('_form', ['model' => $model]);

backend/views/post/index.php
<?php
/**
 * @var $this yii\web\View
 * @var $searchModel backend\models\CategorySearch
 * @var $dataProvider yii\data\ActiveDataProvider
 */

use common\models\User;
use yii\grid\GridView;
use yii\helpers\Html;

$this->title = 'Список постов';
?>
    <h2 class="page-title"><?= $this->title ?></h2>
<?php if (\Yii::$app->user->can(User::POST_CREATE)): ?>
    <?= Html::a('Новый пост', ['create'], ['class' => 'btn btn-sm btn-primary js-show-modal']) ?>
<?php endif ?>

<?= $this->render('_search', ['model' => $searchModel]); ?>

<?= GridView::widget(
    [
        'tableOptions' => ['class' => 'table table-striped'],
        'dataProvider' => $dataProvider,
        'pager' => ['maxButtonCount' => 20],
        'columns' => [
            'id',
            'title',
            'status:postStatusName',
            'created_at:datetime',
            'updated_at:datetime',
            'published_at:datetime',
            'user.email:text:Автор',
            [
                'class' => \yii\grid\ActionColumn::class,
                'template' => '{update}',
                'visibleButtons' => [
                    'update' => Yii::$app->user->can(User::POST_UPDATE),
                ],
                'buttons' => [
                    'update' => function ($url) {
                        return Html::a(
                            '<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>',
                            $url,
                            ['title' => 'Редактировать']
                        );
                    },
                ],
            ],
        ],
    ]
);

backend/views/post/update.php
<?php
/**
 * @var $this \yii\web\View
 * @var $model \common\models\Post
 */
$this->title = 'Редактирование поста: '.$model->title;

echo $this->render('_form', ['model' => $model]);