common/models/Category.php
<?php

namespace common\models;

use yii\behaviors\SluggableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%category}}".
 *
 * @property integer $id
 * @property string $name
 * @property string $slug
 * @property string $description
 * @property string $icon
 * @property string $status
 * @property string $seo_title
 * @property string $seo_description
 * @property string $seo_keywords
 * @property-read string $statusName
 * @property string $created_at
 * @property string $updated_at
 * @property int $rate_sum
 * @property int $rate_count
 */
class Category extends ActiveRecord
{
    public const STATUS_ACTIVE = 'active';
    public const STATUS_DELETED = 'deleted';

    /**
     * @return CategoryQuery
     */
    public static function find()
    {
        return new CategoryQuery(static::class);
    }

    public static function tableName(): string
    {
        return '{{%category}}';
    }

    public function rules(): array
    {
        return [
            [['name', 'seo_title', 'seo_description', 'seo_keywords'], 'trim'],
            ['name', 'required'],
            [['name', 'icon', 'seo_title', 'seo_description', 'seo_keywords'], 'string', 'max' => 255],
            ['description', 'safe'],
            ['status', 'default', 'value' => self::STATUS_DELETED],
            ['status', 'in', 'range' => array_keys(static::getStatusList())],
        ];
    }

    public static function getStatusList(): array
    {
        return [
            self::STATUS_ACTIVE => 'Активен',
            self::STATUS_DELETED => 'Удален',
        ];
    }

    public function attributeLabels(): array
    {
        return [
            'name' => 'Наименование',
            'status' => 'Статус',
            'statusName' => 'Статус',
            'created_at' => 'Создан',
            'updated_at' => 'Изменен',
            'icon' => 'Иконка',
            'description' => 'Описание',
        ];
    }

    public function behaviors(): array
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => function () {
                    return date('Y-m-d H:i:s');
                },
            ],
            [
                'class' => SluggableBehavior::class,
                'attribute' => 'name',
                'ensureUnique' => true,
            ],
        ];
    }

    public function getRate()
    {
        return $this->rate_count ? round($this->rate_sum / $this->rate_count) : 0;
    }

    public function getFormattedRateCount()
    {
        return \Yii::t(
            'app',
            '{n, plural, =0{нет оценок} =1{одна оценка} one{# оценка} few{# оценки} many{# оценок} other{# оценки}}',
            ['n' => $this->rate_count]
        );
    }
}

backend/controllers/CategoryController.php
<?php

namespace backend\controllers;

use backend\models\CategorySearch;
use common\models\Category;
use common\models\User;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class CategoryController extends Controller
{
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'denyCallback' => function () {
                    \Yii::$app->user->loginRequired();
                },
                'rules' => [
                    ['actions' => ['index'], 'allow' => true, 'roles' => [User::CATEGORY_LIST]],
                    ['actions' => ['create'], 'allow' => true, 'roles' => [User::CATEGORY_CREATE]],
                    ['actions' => ['update'], 'allow' => true, 'roles' => [User::CATEGORY_UPDATE]],
                ],
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new CategorySearch();
        $dataProvider = $searchModel->search(\Yii::$app->request->queryParams);

        return $this->render('index', ['dataProvider' => $dataProvider, 'searchModel' => $searchModel]);
    }

    /**
     * @return string
     */
    public function actionCreate()
    {
        $model = new Category();
        if ($model->load(\Yii::$app->request->post()) && $model->save()) {
            return '';
        }

        return $this->renderPartial('_form', ['model' => $model]);
    }

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        /** @var Category $model */
        $model = Category::findOne($id);
        if (!$model) {
            throw new NotFoundHttpException('Категория не найдена');
        }
        if ($model->load(\Yii::$app->request->post()) && $model->save()) {
            return '';
        }

        return $this->renderPartial('_form', ['model' => $model]);
    }
}

frontend/controllers/CategoryController.php
<?php

namespace frontend\controllers;

use common\models\Category;
use common\models\Offer;
use common\models\Seo;
use frontend\helpers\OfferUsed;
use frontend\models\CategoryRate;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class CategoryController extends Controller
{
    /**
     * @return string
     */
    public function actionIndex()
    {
        $categories = Category::find()->active()->select('id, name, slug, icon')->asArray()->all();
        $seo = Seo::findOne(['page' => Seo::CATEGORY_PAGE]);

        return $this->render('index', ['categories' => $categories, 'seo' => $seo]);
    }

    /**
     * @param $slug
     * @param null $page
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionView($slug, $page = null)
    {
        /** @var Category $model */
        $model = Category::find()->active()->slug($slug)->one();
        if (!$model) {
            throw new NotFoundHttpException;
        }

        $dataProvider = new ActiveDataProvider(
            [
                'query' => Offer::find()->innerJoin(
                    '{{%offer_category}} oc',
                    'oc.offer_id={{%offer}}.id and oc.category_id=:category_id',
                    [':category_id' => $model->id]
                )->with(['shop'])->valid(),
                'pagination' => [
                    'pageSize' => 6,
                    'defaultPageSize' => 6,
                    'forcePageParam' => false,
                ],
            ]
        );
        $todayUsed = OfferUsed::getToday($dataProvider);

        return $this->render('view', ['model' => $model, 'dataProvider' => $dataProvider, 'todayUsed' => $todayUsed]);
    }

    /**
     * @param $id
     * @return array
     */
    public function actionRate($id)
    {
        $model = new CategoryRate(['id' => $id]);
        \Yii::$app->response->format = Response::FORMAT_JSON;
        if ($model->load(\Yii::$app->request->post(), '') && $model->save()) {
            return [
                'success' => true,
                'rate' => $model->getCategoryRate(),
                'count' => $model->getCategoryRateCount(),
            ];
        }

        return ['success' => false, 'errors' => $model->getErrors()];
    }
}

frontend/views/category/index.php
<?php
/**
 * @var yii\web\View $this
 * @var array $categories
 * @var $seo \common\models\Seo
 */

use common\helpers\Image;
use yii\helpers\Html;

if ($seo) {
    $this->title = $seo->seo_title;
    $this->params['description'] = $seo->seo_description;
    $this->params['keywords'] = $seo->seo_keywords;
} else {
    $this->title = 'Все категории';
    $this->params['description'] = '';
    $length = 0;
    foreach ($categories as $category) {
        $this->params['description'] .= '· '.$category['name'].' ';
        $length += 3 + mb_strlen($category['name']);
        if ($length >= 155) {
            break;
        }
    }
}
$this->params['image'] = \Yii::$app->params['logo'];
$this->params['breadcrumbs'][] = $this->title;
?>
<h1>Все категории</h1>
<div class="row">
    <div class="page-header"></div>
    <ul class="list-inline category-list" style="list-style-type: none; padding-left: 0">
        <?php foreach ($categories as $category): ?>
            <li style="text-transform: uppercase;">
                <?= Html::a(
                    Html::img(
                        Image::url($category['icon'], 50, 50),
                        ['alt' => $category['name'], 'title' => $category['name'], 'style' => 'margin-right: 10px']
                    ).' '.$category['name'],
                    ['category/view', 'slug' => $category['slug']],
                    ['title' => $category['name']]
                ) ?>
            </li>
        <?php endforeach ?>
    </ul>
</div>

frontend/views/category/view.php
<?php
/**
 * @var yii\web\View $this
 * @var common\models\Category $model
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var int[] $todayUsed
 */

use common\helpers\Image;
use frontend\widgets\NewShops;
use frontend\widgets\RateWidget;
use yii\helpers\Html;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\widgets\ListView;

if ($model->seo_title) {
    $this->title = $model->seo_title;
} else {
    $this->title = "Промокоды на {$model->name}";
}
if ($model->seo_description) {
    $this->params['description'] = $model->seo_description;
} else {
    $this->params['description'] = "Только действующие промокоды на {$model->name} ➤ скидки до ㊿% ➤ подарки ➤ бесплатная доставка";
}
if ($model->seo_keywords) {
    $this->params['keywords'] = $model->seo_keywords;
}
$this->params['image'] = $model->icon;
$this->params['breadcrumbs'][] = ['label' => 'Все категории', 'url' => ['category/index']];
$this->params['breadcrumbs'][] = $model->name;
if ($dataProvider->pagination->page) {
    $this->title .= ' | Страница '.(1 + $dataProvider->pagination->page);
    $this->params['description'] .= ' | Страница '.(1 + $dataProvider->pagination->page);
}
$params = Json::encode(['url' => Url::to(['category/rate', 'id' => $model->id])]);
$this->registerJs("$('#js-category-rating').StarRating({$params});");
$this->registerJsFile('//yastatic.net/es5-shims/0.0.2/es5-shims.min.js');
$this->registerJsFile('//yastatic.net/share2/share.js');

?>
<div class="row">
    <main class="col-lg-17 col-xl-18">
        <h1>Промокоды на <?= $model->name ?> <?= $dataProvider->pagination->page ? Yii::t(
                'app',
                '<small>страница {n}</small>',
                ['n' => $dataProvider->pagination->page + 1]
            ) : '' ?></h1>
        <?= ListView::widget(
            [
                'dataProvider' => $dataProvider,
                'itemView' => '@frontend/views/offer/_offer',
                'viewParams' => ['todayUsed' => $todayUsed],
                'pager' => [
                    'options' => ['class' => 'pagination'],
                    'linkContainerOptions' => ['class' => 'page-item'],
                    'linkOptions' => ['class' => 'page-link'],
                    'disabledListItemSubTagOptions' => ['class' => 'page-link', 'tag' => 'a', 'href' => '#'],
                ],
                'options' => [
                    'class' => 'coupon-list',
                ],
                'itemOptions' => [
                    'class' => 'card coupon',
                ],
                'summary' => false,
            ]
        ) ?>
        <div>
            <?= nl2br($model->description) ?>
        </div>
    </main>
    <div class="col-lg-7 col-xl-6">
        <div class="text-center image">
            <?= Html::img(
                Image::url($model->icon, 240, 180),
                ['alt' => $model->name, 'title' => $model->name, 'class' => 'img-fluid']
            ) ?>
            <div class="aggregateRating category" itemprop="aggregateRating" itemscope
                 itemtype="http://schema.org/AggregateRating">
                <?= RateWidget::widget(['value' => $model->getRate(), 'id' => 'js-category-rating']) ?>
                <div>
                    <span class="svg--user svg-icon" data-grunticon-embed></span>
                    <span class="js-rate-count"><?= $model->getFormattedRateCount() ?></span>
                    <meta content="<?= $model->rate_count ?>" itemprop="reviewCount"/>
                    <meta content="<?= $model->getRate() ?>" itemprop="ratingValue"/>
                </div>
            </div>
            <div class="ya-share2"
                 data-services="vkontakte,facebook,odnoklassniki,twitter,viber,whatsapp,skype,telegram"></div>
        </div>
        <?= NewShops::widget(); ?>
    </div>
</div>